In [162]:
!nvidia-smi

Tue Mar 24 16:02:16 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P0             28W /   70W |     383MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            6563      C   /usr/bin/python3                        380MiB |
+-----------------------------------------------------------------------------------------+

In [163]:
15360/1024   # 15 GB GPU

15.0

In [164]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [165]:
df=pd.read_csv('/content/income.csv')
df

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income_level
0,39,77516,13,2174,0,40,0
1,50,83311,13,0,0,13,0
2,38,215646,9,0,0,40,0
3,53,234721,7,0,0,40,0
4,28,338409,13,0,0,40,0
...,...,...,...,...,...,...,...
48837,39,215419,13,0,0,36,0
48838,64,321403,9,0,0,40,0
48839,38,374983,13,0,0,50,0
48840,44,83891,13,5455,0,40,0
48841,35,182148,13,0,0,60,1

In [166]:
df.shape

(48842, 7)

In [167]:
df.isnull().sum()

age               0
fnlwgt            0
education_num     0
capital_gain      0
capital_loss      0
hours_per_week    0
income_level      0
dtype: int64

In [168]:
training_data=df.iloc[:40000,:]
validation_data=df.iloc[40000:45000,:]
testing_data=df.iloc[45000:]

In [169]:
training_data.shape

(40000, 7)

In [170]:
validation_data.shape

(5000, 7)

In [171]:
testing_data.shape

(3842, 7)

In [172]:
training_data_inde=training_data.iloc[:,:-1]
training_data_dep=training_data.iloc[:,-1]

In [173]:
validation_data_inde=validation_data.iloc[:,:-1]
validation_data_dep=validation_data.iloc[:,-1]

In [174]:
testing_data_inde=testing_data.iloc[:,:-1]
testing_data_dep=testing_data.iloc[:,-1]

#Design the Binary ANN Architecure

In [175]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
from tensorflow.keras.activations import relu,softmax

In [176]:
training_data_inde.shape[1]

6

In [177]:
import warnings
warnings.filterwarnings('ignore')

In [178]:
model=Sequential()

# input_layers to hiddel layer 1
model.add(Dense(units=10,
                kernel_initializer='he_uniform',
                activation='relu',
                input_dim=training_data_inde.shape[1]))

# hiddel layer 1 to hidden layer 2
model.add(Dense(units=4,kernel_initializer='he_uniform',activation='relu'))

# hiddel layer 2 to hidden layer 3
model.add(Dense(units=2,kernel_initializer='he_uniform',activation='relu'))

# hiddel layer 3 to outputlayer
model.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [179]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['Accuracy'])

In [180]:
40000/1000

40.0

In [181]:
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_37 (Dense)                │ (None, 10)             │            70 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_39 (Dense)                │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_40 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 127 (508.00 B)

 Trainable params: 127 (508.00 B)

 Non-trainable params: 0 (0.00 B)

In [182]:
# Training _process

model.fit(training_data_inde,
          training_data_dep,
          batch_size=1000,
          epochs=5,
          validation_data=(validation_data_inde,validation_data_dep))

Epoch 1/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - Accuracy: 0.7604 - loss: 0.6881 - val_Accuracy: 0.7674 - val_loss: 0.6826
Epoch 2/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6782 - val_Accuracy: 0.7674 - val_loss: 0.6728
Epoch 3/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6689 - val_Accuracy: 0.7674 - val_loss: 0.6635
Epoch 4/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6601 - val_Accuracy: 0.7674 - val_loss: 0.6547
Epoch 5/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 0.7604 - loss: 0.6518 - val_Accuracy: 0.7674 - val_loss: 0.6465

In [183]:
model.weights

[<Variable path=sequential_21/dense_37/kernel, shape=(6, 10), dtype=float32, value=[[ 0.686476    0.14251494 -0.5889747  -0.5956013  -0.80921173  0.45844054
    0.5353441   0.02171707  0.14209485 -0.5669863 ]
  [ 0.35721302 -0.13152146 -0.15859866  0.8933208   0.00202322  0.91160154
   -0.88773274  0.8384979  -0.10506368  0.915514  ]
  [ 0.6963544  -0.4039781   0.11347532  0.407377   -0.57978225  0.48724937
    0.48019361 -0.7333462  -0.6516316  -0.09352016]
  [ 0.9981413   0.1297741   0.6845026   0.83376646  0.41840577 -0.4594841
   -0.8936825  -0.15584087 -0.7136767   0.38599753]
  [-0.6810479  -0.7684696  -0.63127327 -0.99571824  0.3671441  -0.88437605
   -0.79933953 -0.5941837  -0.5721357  -0.88537383]
  [ 0.30987167 -0.53390193 -0.7977483  -0.15173435 -0.05227494  0.16384792
    0.6283288   0.44778514  0.6615541   0.40375066]]>,
 <Variable path=sequential_21/dense_37/bias, shape=(10,), dtype=float32, value=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]>,
 <Variable path=sequential_21/dense_38/kernel, shape=(10, 4), dtype=float32, value=[[-0.19488525 -0.49198562 -0.03217226  0.03706014]
  [ 0.05051911  0.08080709  0.51899886  0.10358435]
  [-0.15111446  0.7146088   0.67867017  0.2974882 ]
  [ 0.05605042 -0.23157597 -0.4395187   0.04664123]
  [ 0.555359   -0.44675255 -0.04991817 -0.30003121]
  [ 0.16634172 -0.5120799  -0.50670266 -0.38035113]
  [-0.40016487 -0.0804621   0.39352643  0.6765449 ]
  [ 0.13279772  0.2759881   0.56660354  0.15077388]
  [ 0.5121299   0.33858907 -0.45034713 -0.40563542]
  [-0.42326832 -0.36715105 -0.06319469 -0.3073166 ]]>,
 <Variable path=sequential_21/dense_38/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>,
 <Variable path=sequential_21/dense_39/kernel, shape=(4, 2), dtype=float32, value=[[-0.54997045 -0.28882873]
  [ 0.76012754 -0.43782657]
  [-0.49505132  0.4780954 ]
  [ 0.4899019  -0.50897837]]>,
 <Variable path=sequential_21/dense_39/bias, shape=(2,), dtype=float32, value=[0. 0.]>,
 <Variable path=sequential_21/dense_40/kernel, shape=(2, 1), dtype=float32, value=[[0.00504005]
  [1.2340285 ]]>,
 <Variable path=sequential_21/dense_40/bias, shape=(1,), dtype=float32, value=[-0.19178818]>]

In [186]:
testing_data_inde.shape

(3842, 6)

In [188]:
testing_data_inde.head(1)

       age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week
45000   19  124906             10             0          1719              25

In [193]:
if model.predict(np.array([[19 , 124906 , 10,0,1719,25]]))[0][0] > 0.5:
  print(f'good income {1}')
else:
  print(f'bad income {0}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
bad income 0

In [195]:
r=model.predict(testing_data_inde)
r

121/121 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[0.4521994],
       [0.4521994],
       [0.4521994],
       ...,
       [0.4521994],
       [0.4521994],
       [0.4521994]], dtype=float32)

In [201]:
c=[]
for i in r:
  if i[0]>0.5:
    c.append(1)
  else:
    c.append(0)

In [204]:
len(c)

3842

In [205]:
c

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [206]:
testing_data_dep

45000    0
45001    0
45002    1
45003    0
45004    0
        ..
48837    0
48838    0
48839    0
48840    0
48841    1
Name: income_level, Length: 3842, dtype: int64

In [208]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [209]:
confusion_matrix(testing_data_dep,c)

array([[2902,    0],
       [ 940,    0]])

In [211]:
accuracy_score(testing_data_dep,c)

0.7553357626236336

In [212]:
print(classification_report(testing_data_dep,c))

              precision    recall  f1-score   support

           0       0.76      1.00      0.86      2902
           1       0.00      0.00      0.00       940

    accuracy                           0.76      3842
   macro avg       0.38      0.50      0.43      3842
weighted avg       0.57      0.76      0.65      3842